"""added name camp to TourGuide model

Revision ID: 03f0c02e86bf
Revises: 607ac30e99fb
Create Date: 2025-12-28 16:10:50.513600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '03f0c02e86bf'
down_revision: Union[str, Sequence[str], None] = '607ac30e99fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourist_guide_tb', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tourist_guide_tb', 'name')
    # ### end Alembic commands ###
