"""adding new model Tourist

Revision ID: 14bd9a1938f7
Revises: 675e565b9530
Create Date: 2025-12-26 21:42:15.780346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '14bd9a1938f7'
down_revision: Union[str, Sequence[str], None] = '675e565b9530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('tourists_tb',
    sa.Column('tourist_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('localization', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_tb.user_id'], ),
    sa.PrimaryKeyConstraint('tourist_id'),
    sa.UniqueConstraint('tourist_id')
    )
    op.create_geospatial_index('idx_tourists_tb_localization', 'tourists_tb', ['localization'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_column('tourist_guide_tb', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tourist_guide_tb', sa.Column('cadastur', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('tourist_guide_tb', 'number_phone')
    op.add_column('users_tb', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_geospatial_index(op.f('idx_users_tb_localization'), table_name='users_tb', postgresql_using='gist', column_name='localization')
    op.create_index(op.f('ix_users_tb_email'), 'users_tb', ['email'], unique=True)
    op.drop_column('users_tb', 'username')
    op.drop_column('users_tb', 'name')
    op.drop_column('users_tb', 'role')
    op.drop_geospatial_column('users_tb', 'localization')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('users_tb', sa.Column('localization', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=True))
    op.add_column('users_tb', sa.Column('role', sa.VARCHAR(), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users_tb', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users_tb', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_tb_email'), table_name='users_tb')
    op.create_geospatial_index(op.f('idx_users_tb_localization'), 'users_tb', ['localization'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.drop_column('users_tb', 'is_active')
    op.add_column('tourist_guide_tb', sa.Column('number_phone', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tourist_guide_tb', 'cadastur')
    op.drop_column('tourist_guide_tb', 'phone')
    op.drop_geospatial_index('idx_tourists_tb_localization', table_name='tourists_tb', postgresql_using='gist', column_name='localization')
    op.drop_geospatial_table('tourists_tb')
    # ### end Alembic commands ###
