"""fixing table names

Revision ID: 1cdc978cf5cb
Revises: 
Create Date: 2025-12-23 21:27:17.688326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cdc978cf5cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_tb',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('city_id'),
    sa.UniqueConstraint('city_id')
    )
    op.create_table('tag_tb',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_id')
    )
    op.create_geospatial_table('users_tb',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('localization', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_geospatial_index('idx_users_tb_localization', 'users_tb', ['localization'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('tourist_guide_tb',
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('number_phone', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_tb.user_id'], ),
    sa.PrimaryKeyConstraint('guide_id'),
    sa.UniqueConstraint('guide_id')
    )
    op.create_geospatial_table('tourist_spot_tb',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('localization', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('time_open', postgresql.TIME(), nullable=True),
    sa.Column('time_close', postgresql.TIME(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tour_guide_id', sa.Uuid(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city_tb.city_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_guide_id'], ['tourist_guide_tb.guide_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('spot_id'),
    sa.UniqueConstraint('spot_id')
    )
    op.create_geospatial_index('idx_tourist_spot_tb_localization', 'tourist_spot_tb', ['localization'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('event_tb',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_event', sa.DATE(), nullable=True),
    sa.Column('time_start', postgresql.TIME(), nullable=True),
    sa.Column('time_end', postgresql.TIME(), nullable=True),
    sa.Column('tourist_spot_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_spot_id'], ['tourist_spot_tb.spot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('spot_tags',
    sa.Column('spot_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['tourist_spot_tb.spot_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_tb.tag_id'], ),
    sa.PrimaryKeyConstraint('spot_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot_tags')
    op.drop_table('event_tb')
    op.drop_geospatial_index('idx_tourist_spot_tb_localization', table_name='tourist_spot_tb', postgresql_using='gist', column_name='localization')
    op.drop_geospatial_table('tourist_spot_tb')
    op.drop_table('tourist_guide_tb')
    op.drop_geospatial_index('idx_users_tb_localization', table_name='users_tb', postgresql_using='gist', column_name='localization')
    op.drop_geospatial_table('users_tb')
    op.drop_table('tag_tb')
    op.drop_table('city_tb')
    # ### end Alembic commands ###
