"""removing localization attribute

Revision ID: 82d19486bdf8
Revises: 03f0c02e86bf
Create Date: 2026-01-05 14:28:42.078606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '82d19486bdf8'
down_revision: Union[str, Sequence[str], None] = '03f0c02e86bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(op.f('idx_tourists_tb_localization'), table_name='tourists_tb', postgresql_using='gist', column_name='localization')
    op.drop_geospatial_column('tourists_tb', 'localization')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('tourists_tb', sa.Column('localization', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), autoincrement=False, nullable=True))
    op.create_geospatial_index(op.f('idx_tourists_tb_localization'), 'tourists_tb', ['localization'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###
