"""fixing model User including role

Revision ID: 9b16ef760871
Revises: a16264c53c9a
Create Date: 2025-12-27 17:29:13.828642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9b16ef760871'
down_revision: Union[str, Sequence[str], None] = 'a16264c53c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tb', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    op.drop_column('users_tb', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tb', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users_tb', 'role')
    # ### end Alembic commands ###
