"""fixing TourGuideModel

Revision ID: a16264c53c9a
Revises: 14bd9a1938f7
Create Date: 2025-12-27 16:01:29.805068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a16264c53c9a'
down_revision: Union[str, Sequence[str], None] = '14bd9a1938f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tourists_tb', ['tourist_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tourists_tb', type_='unique')
    # ### end Alembic commands ###
