"""adding ondelete cascade in some models

Revision ID: e2197553f3e4
Revises: 82d19486bdf8
Create Date: 2026-01-05 14:37:23.387774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e2197553f3e4'
down_revision: Union[str, Sequence[str], None] = '82d19486bdf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tourist_guide_tb_user_id_fkey'), 'tourist_guide_tb', type_='foreignkey')
    op.create_foreign_key(None, 'tourist_guide_tb', 'users_tb', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tourists_tb_user_id_fkey'), 'tourists_tb', type_='foreignkey')
    op.create_foreign_key(None, 'tourists_tb', 'users_tb', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tourists_tb', type_='foreignkey')
    op.create_foreign_key(op.f('tourists_tb_user_id_fkey'), 'tourists_tb', 'users_tb', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'tourist_guide_tb', type_='foreignkey')
    op.create_foreign_key(op.f('tourist_guide_tb_user_id_fkey'), 'tourist_guide_tb', 'users_tb', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
