"""adding role camp

Revision ID: ed0064b14cff
Revises: f898b1f306f4
Create Date: 2025-12-24 16:53:33.566698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ed0064b14cff'
down_revision: Union[str, Sequence[str], None] = 'f898b1f306f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activity_tb', ['activity_id'])
    op.add_column('users_tb', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_tb', 'role')
    op.drop_constraint(None, 'activity_tb', type_='unique')
    # ### end Alembic commands ###
