"""adding table activity

Revision ID: f898b1f306f4
Revises: 1cdc978cf5cb
Create Date: 2025-12-24 15:24:22.223377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f898b1f306f4'
down_revision: Union[str, Sequence[str], None] = '1cdc978cf5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_tb',
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tourist_spot_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tourist_spot_id'], ['tourist_spot_tb.spot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id'),
    sa.UniqueConstraint('activity_id')
    )
    op.create_unique_constraint(None, 'city_tb', ['city_id'])
    op.create_unique_constraint(None, 'event_tb', ['event_id'])
    op.create_unique_constraint(None, 'tag_tb', ['tag_id'])
    op.create_unique_constraint(None, 'tourist_guide_tb', ['guide_id'])
    op.create_unique_constraint(None, 'tourist_spot_tb', ['spot_id'])
    op.create_unique_constraint(None, 'users_tb', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_tb', type_='unique')
    op.drop_constraint(None, 'tourist_spot_tb', type_='unique')
    op.drop_constraint(None, 'tourist_guide_tb', type_='unique')
    op.drop_constraint(None, 'tag_tb', type_='unique')
    op.drop_constraint(None, 'event_tb', type_='unique')
    op.drop_constraint(None, 'city_tb', type_='unique')
    op.drop_table('activity_tb')
    # ### end Alembic commands ###
